
const
  ACTION_MASK* = 0xff
  ACTION_POINTER_INDEX_MASK* = 0xff00

  ACTION_POINTER_INDEX_SHIFT* = 8

  ACTION_DOWN* = 0
  ACTION_UP* = 1
  ACTION_MOVE* = 2
  ACTION_CANCEL* = 3
  ACTION_OUTSIDE* = 4
  ACTION_POINTER_DOWN* = 5
  ACTION_POINTER_UP* = 6
  ACTION_HOVER_MOVE* = 7
  ACTION_SCROLL* = 8
  ACTION_HOVER_ENTER* = 9
  ACTION_HOVER_EXIT* = 10
  ACTION_BUTTON_PRESS* = 11
  ACTION_BUTTON_RELEASE* = 12

  FLAG_WINDOW_IS_OBSCURED* = 0x1
  FLAG_WINDOW_IS_PARTIALLY_OBSCURED* = 0x2
  FLAG_HOVER_EXIT_PENDING* = 0x4
  FLAG_IS_GENERATED_GESTURE* = 0x8
  FLAG_CANCELED* = 0x20
  FLAG_NO_FOCUS_CHANGE* = 0x40
  FLAG_TAINTED* = 0x80000000
  FLAG_TARGET_ACCESSIBILITY_FOCUS* = 0x40000000

  EDGE_TOP* = 0x1
  EDGE_BOTTOM* = 0x2
  EDGE_LEFT* = 0x4
  EDGE_RIGHT* = 0x8

  AXIS_X* = 0
  AXIS_Y* = 1
  AXIS_PRESSURE* = 2
  AXIS_SIZE* = 3
  AXIS_TOUCH_MAJOR* = 4
  AXIS_TOUCH_MINOR* = 5
  AXIS_TOOL_MAJOR* = 6
  AXIS_TOOL_MINOR* = 7
  AXIS_ORIENTATION* = 8
  AXIS_VSCROLL* = 9
  AXIS_HSCROLL* = 10
  AXIS_Z* = 11
  AXIS_RX* = 12
  AXIS_RY* = 13
  AXIS_RZ* = 14
  AXIS_HAT_X* = 15
  AXIS_HAT_Y* = 16
  AXIS_LTRIGGER* = 17
  AXIS_RTRIGGER* = 18
  AXIS_THROTTLE* = 19
  AXIS_RUDDER* = 20
  AXIS_WHEEL* = 21
  AXIS_GAS* = 22
  AXIS_BRAKE* = 23
  AXIS_DISTANCE* = 24
  AXIS_TILT* = 25
  AXIS_SCROLL* = 26
  AXIS_RELATIVE_X* = 27
  AXIS_RELATIVE_Y* = 28
  AXIS_GENERIC_1* = 32
  AXIS_GENERIC_2* = 33
  AXIS_GENERIC_3* = 34
  AXIS_GENERIC_4* = 35
  AXIS_GENERIC_5* = 36
  AXIS_GENERIC_6* = 37
  AXIS_GENERIC_7* = 38
  AXIS_GENERIC_8* = 39
  AXIS_GENERIC_9* = 40
  AXIS_GENERIC_10* = 41
  AXIS_GENERIC_11* = 42
  AXIS_GENERIC_12* = 43
  AXIS_GENERIC_13* = 44
  AXIS_GENERIC_14* = 45
  AXIS_GENERIC_15* = 46
  AXIS_GENERIC_16* = 47
  AXIS_GESTURE_X_OFFSET* = 48
  AXIS_GESTURE_Y_OFFSET* = 49
  AXIS_GESTURE_SCROLL_X_DISTANCE* = 50
  AXIS_GESTURE_SCROLL_Y_DISTANCE* = 51
  AXIS_GESTURE_PINCH_SCALE_FACTOR* = 52

  BUTTON_PRIMARY* = 1 shl 0
  BUTTON_SECONDARY* = 1 shl 1
  BUTTON_TERTIARY* = 1 shl 2
  BUTTON_BACK* = 1 shl 3
  BUTTON_FORWARD* = 1 shl 4
  BUTTON_STYLUS_PRIMARY* = 1 shl 5
  BUTTON_STYLUS_SECONDARY* = 1 shl 6

  CLASSIFICATION_NONE* = 0
  CLASSIFICATION_AMBIGUOUS_GESTURE* = 1
  CLASSIFICATION_DEEP_PRESS* = 2
  CLASSIFICATION_TWO_FINGER_SWIPE* = 3
  CLASSIFICATION_MULTI_FINGER_SWIPE* = 4
  CLASSIFICATION_PINCH* = 5

  TOOL_TYPE_UNKNOWN* = 0
  TOOL_TYPE_FINGER* = 1
  TOOL_TYPE_STYLUS* = 2
  TOOL_TYPE_MOUSE* = 3
  TOOL_TYPE_ERASER* = 4
  TOOL_TYPE_PALM* = 5
